// This file is auto-generated by GitHub Actions
// Do not edit manually - it will be overwritten on each push
// Generated from ALCHEMY_PRIMARY_KEY repository secret
// Version hash: f66a4a4c
window.ALCHEMY_KEYS_CONFIG = {
    primary: "rBPB_PNiwCwtVDkl6rvRv"
};
