// This file is auto-generated by GitHub Actions
// Do not edit manually - it will be overwritten on each push
// This file is generated from the ALCHEMY_PRIMARY_KEY secret in GitHub
// If this file shows primary: null, the GitHub Actions workflow needs to run to generate it
window.ALCHEMY_KEYS_CONFIG = {
    primary: null
};
