// This file is auto-generated by GitHub Actions
// Do not edit manually - it will be overwritten on each push
// La primary key se inyectará desde GitHub Secrets cuando el workflow se ejecute
window.ALCHEMY_KEYS_CONFIG = {
    primary: "pqRmKgTaLqm2eak9iML1f", // Placeholder - será reemplazado por GitHub Actions
    fallbacks: ["pqRmKgTaLqm2eak9iML1f"]
};
