export const ZERO_MOVIES_FACET_ABI = [
  {
    type: 'function',
    name: 'mintMovie',
    inputs: [{ name: 'movieId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getAllMovies',
    inputs: [],
    outputs: [
      { name: 'ids', type: 'uint256[]' },
      { name: 'names', type: 'string[]' },
      { name: 'mintedFlags', type: 'bool[]' },
      { name: 'activeFlags', type: 'bool[]' },
      { name: 'tokenIds', type: 'uint256[]' },
      { name: 'minters', type: 'address[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAvailableMovies',
    inputs: [],
    outputs: [
      { name: 'ids', type: 'uint256[]' },
      { name: 'names', type: 'string[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getMovie',
    inputs: [{ name: 'movieId', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'name', type: 'string' },
      { name: 'minted', type: 'bool' },
      { name: 'active', type: 'bool' },
      { name: 'tokenId', type: 'uint256' },
      { name: 'mintedBy', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserMovieMintCount',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getZEROmoviesConfig',
    inputs: [],
    outputs: [
      { name: 'delegator', type: 'address' },
      { name: 'defaultPrice', type: 'uint256' },
      { name: 'burnOnMint', type: 'bool' },
      { name: 'paused', type: 'bool' },
      { name: 'maxPerWallet', type: 'uint256' },
      { name: 'totalMinted', type: 'uint256' },
      { name: 'totalZeroBurned', type: 'uint256' },
      { name: 'movieCount', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'zeroMoviesTotalMinted',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'MovieMinted',
    inputs: [
      { name: 'minter', type: 'address', indexed: true },
      { name: 'movieId', type: 'uint256', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
      { name: 'zeroPaid', type: 'uint256', indexed: false },
      { name: 'burned', type: 'bool', indexed: false },
    ],
  },
] as const;
