// This file is auto-generated by GitHub Actions
// Do not edit manually - it will be overwritten on each push
window.ALCHEMY_KEYS_CONFIG = {
    primary: "QuzuDRVmaHPyKNL-HaZwA",
    fallbacks: ["pqRmKgTaLqm2eak9iML1f"]
};
