[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3001"
CORS_ORIGIN = "https://adrianzero.com"
CONTRACT_ADDRESS = "0x90546848474fb3c9fda3fdad887969bb244e7e58"
ADMIN_WALLET = "0x4943407105999e3E97EFA2035F5cbC64D72581C6"
RPC_URL = "https://mainnet.base.org"
CHAIN_ID = "8453"
